############################# Input #####################################
filebeat.inputs:
- type: log
  paths: 
  - /var/log/access.log
  fields:
    logzio_codec: plain
    token: LOGZIO-TOKEN
    type: nginx_access
  fields_under_root: true
  encoding: utf-8
  ignore_older: 3h

- type: log
  paths: 
  - /var/log/error.log
  fields:
    logzio_codec: plain
    token: LOGZIO-TOKEN
    type: nginx_error
  fields_under_root: true
  encoding: utf-8
  ignore_older: 3h

registry_file: /var/lib/filebeat/registry
############################# Output ##########################################
output.logstash:
  hosts: ["LOGZIO-LISTENER:5015"]
  ssl:
    certificate_authorities: ['/etc/pki/tls/certs/COMODORSADomainValidationSecureServerCA.crt']
